### ISSUE TITLE
train_prefix = args[1] IndexError: list index out of range

### ISSUE THREAD

**Issue by qingxin-meng** [dallascard/scholar#1]
It is alright to use the package for torch version, but when I run it with tf version, it pops the error:
```
train_prefix = args[1]
IndexError: list index out of range 
```

The code I use is : 
```
python run_scholar_tf.py data/imdb/processed/ -k 10 --test test --labels sentiment
```

How can I fix it ?

**Comment by dallascard** [comment]
My apologies. I had forgotten to update the tensorflow interface to match the pytorch one. However, I have just pushed an update that brings it closer to being the same. If you pull the latest update, your command should now run. For more examples with the tensorflow model, please have a look at the tutorial.txt file (though I would still recommend using the pytorch one).

**Comment by qingxin-meng** [comment]
Thanks a lot!
