### ISSUE TITLE
Incorrect command given in the README for preprocessing

### ISSUE THREAD

**Issue by Pranav-Goel** [dallascard/scholar#3]
I think the example command for preprocessing in the README: `python preprocess_data.py data/imdb/train.jsonlist data/imdb/processed/ --vocab-size 2000 --label sentiment --test-prefix data/imdb/test.jsonlist`
should instead be: `python preprocess_data.py data/imdb/train.jsonlist data/imdb/processed/ --vocab-size 2000 --label sentiment --test data/imdb/test.jsonlist`

**Comment by dallascard** [comment]
You are absolutely right! Thanks for the catch. I have made the change.
