### ISSUE TITLE
Struggling to replicate External NPMI scores

### ISSUE THREAD

**Issue by Pranav-Goel** [dallascard/scholar#4]
Hi Dallas,

I am trying to replicate the external NPMI scores using NYT articles from 2000 to 2009 on IMDB and 20newsgroups. I have no problems replicating the internal NPMI scores.

1. Was the NYT articles vocab size also limited to 5000 when preprocessing?
2. Is it possible to know just the shape of the counts array formed on this external NYT article corpus? 

Currently, if I have one document per one month of NY articles (for a total of just 119), I believe they are so large that the counts become too sparse and I just get NaN when running compute_npmi (whether I limit vocab size to 5000 or not). If I instead split the text up into many smaller documents resulting in a final counts array of the shape - (179787, 5000), I stop getting NaNs but the NPMI score I get for IMDB is around 0.007 which is much lower than reported in the paper. (The command I run to get this score: python compute_npmi.py output_imdb/topics.txt data/nyt_split/processed/train.npz data/imdb/processed/train.vocab.json)

I am sure I am making some mistakes, but I have been unable to figure it out. Any help would be appreciated!

**Comment by dallascard** [comment]
Hey Pranav, sorry about that! I actually treat each NYT article as a separate document, so I end up with  919991 rows. I think you are doing everything else correctly, except that `compute_npmi.py` actually expects a vocabulary file for the reference counts, not for the model. I just pushed two more scripts to the repo and updated the README, which will do the preprocessing of the gigaword data into the proper form. Let me know if you run into any problem!

**Comment by Pranav-Goel** [comment]
Thank you, Dallas, that worked perfectly well!
